// SEO-064 / SEO-077: Allowlist of indexable city × (category|type) intersection pages.
//
// Why this exists: the directory generates ~2,625 programmatic
// /practitioners/area/:city/category/:slug and /practitioners/area/:city/type/:slug
// URLs (21 cities × ~125 categories/types). With <10% unique content per
// combo they look like a doorway cluster to Google. Default behaviour is
// therefore noindex for every intersection, with an explicit allowlist of
// combos that have enough live providers to render genuine directory pages.
//
// Threshold: ≥5 live providers per combo for general specialties; ≥1 for dental
// specialties (Oral Care and dentist/hygienist types) so any dental coverage we
// do have is discoverable. Any combo missing from these arrays continues to
// serve robots="noindex, follow" and is dropped from the sitemap.
//
// Counts in the trailing comments are the live provider counts on production
// at the time the allowlist was generated (geo-radius filter, matching the
// frontend's /user/filter payload). Re-generate with
// /tmp/ph-mongo-probe/compute_prod_geo.js when the practitioner directory
// grows materially — combos drop off the list automatically once they fall
// below threshold (their pages flip back to noindex on the next deploy).
//
// Entry format: `${city}/${slug}` where both sides are the same slug used
// in the URL (city segment as stored in src/app/_helpers/location-data.ts,
// category/type slug as produced by slugify()).

const INDEXABLE_CITY_CATEGORY: ReadonlyArray<string> = [
  // burnaby
  'burnaby/addiction', // Addiction (5 providers)
  'burnaby/ankle-foot', // Ankle/Foot (17 providers)
  'burnaby/back', // Back (18 providers)
  'burnaby/behavioural', // Behavioural (6 providers)
  'burnaby/chronic-disease-management', // Chronic Disease Management (11 providers)
  'burnaby/depression', // Depression (6 providers)
  'burnaby/digestion-and-gut-health', // Digestion and Gut Health (12 providers)
  'burnaby/eating-disorder', // Eating Disorder (5 providers)
  'burnaby/eating-disorder-recovery', // Eating Disorder Recovery (9 providers)
  'burnaby/elbow', // Elbow (15 providers)
  'burnaby/fitness', // Fitness (24 providers)
  'burnaby/food-sensitivities', // Food Sensitivities (10 providers)
  'burnaby/headache', // Headache (16 providers)
  'burnaby/health-condition', // Health Condition (9 providers)
  'burnaby/high-intensity-interval-training', // High Intensity Interval Training (16 providers)
  'burnaby/hip', // Hip (16 providers)
  'burnaby/hormone-imbalance', // Hormone Imbalance (12 providers)
  'burnaby/hormones', // Hormones (7 providers)
  'burnaby/immune-system-and-energy', // Immune System and Energy (9 providers)
  'burnaby/jaw', // Jaw (8 providers)
  'burnaby/knee', // Knee (18 providers)
  'burnaby/maternity-pre-and-postnatal', // Maternity/Pre and Postnatal (7 providers)
  'burnaby/menopause', // Menopause (7 providers)
  'burnaby/mindfulness', // Mindfulness (11 providers)
  'burnaby/mood-mental-health', // Mood/Mental Health (16 providers)
  'burnaby/motivation', // Motivation (11 providers)
  'burnaby/natural-remedies', // Natural Remedies (7 providers)
  'burnaby/neck', // Neck (16 providers)
  'burnaby/nutrition', // Nutrition (14 providers)
  'burnaby/pain-management', // Pain Management (20 providers)
  'burnaby/pilates', // Pilates (11 providers)
  'burnaby/pms', // PMS (7 providers)
  'burnaby/preventative-health', // Preventative Health (9 providers)
  'burnaby/reproductive-health-fertility', // Reproductive Health/Fertility (6 providers)
  'burnaby/running', // Running (14 providers)
  'burnaby/sexual-health', // Sexual Health (5 providers)
  'burnaby/shoulder', // Shoulder (15 providers)
  'burnaby/sports-specific-conditioning', // Sports Specific Conditioning (14 providers)
  'burnaby/strength-training-toning', // Strength Training/Toning (20 providers)
  'burnaby/stress-anxiety', // Stress/Anxiety (12 providers)
  'burnaby/supplements', // Supplements (5 providers)
  'burnaby/weight-management', // Weight Management (12 providers)
  'burnaby/women-s-men-s-health', // Women's/Men's Health (14 providers)
  'burnaby/wrist-hand', // Wrist/Hand (14 providers)
  // coquitlam
  'coquitlam/ankle-foot', // Ankle/Foot (12 providers)
  'coquitlam/attention-focus', // Attention/Focus (5 providers)
  'coquitlam/back', // Back (13 providers)
  'coquitlam/behavioural', // Behavioural (5 providers)
  'coquitlam/chronic-disease-management', // Chronic Disease Management (6 providers)
  'coquitlam/depression', // Depression (12 providers)
  'coquitlam/digestion-and-gut-health', // Digestion and Gut Health (6 providers)
  'coquitlam/elbow', // Elbow (12 providers)
  'coquitlam/fitness', // Fitness (20 providers)
  'coquitlam/food-sensitivities', // Food Sensitivities (5 providers)
  'coquitlam/headache', // Headache (12 providers)
  'coquitlam/high-intensity-interval-training', // High Intensity Interval Training (9 providers)
  'coquitlam/hip', // Hip (12 providers)
  'coquitlam/hormone-imbalance', // Hormone Imbalance (7 providers)
  'coquitlam/jaw', // Jaw (5 providers)
  'coquitlam/knee', // Knee (12 providers)
  'coquitlam/mindfulness', // Mindfulness (10 providers)
  'coquitlam/mood-mental-health', // Mood/Mental Health (15 providers)
  'coquitlam/motivation', // Motivation (10 providers)
  'coquitlam/neck', // Neck (13 providers)
  'coquitlam/nutrition', // Nutrition (7 providers)
  'coquitlam/pain-management', // Pain Management (16 providers)
  'coquitlam/preventative-health', // Preventative Health (9 providers)
  'coquitlam/running', // Running (11 providers)
  'coquitlam/shoulder', // Shoulder (13 providers)
  'coquitlam/sports-specific-conditioning', // Sports Specific Conditioning (13 providers)
  'coquitlam/strength-training-toning', // Strength Training/Toning (17 providers)
  'coquitlam/stress-anxiety', // Stress/Anxiety (13 providers)
  'coquitlam/trauma', // Trauma (6 providers)
  'coquitlam/weight-management', // Weight Management (6 providers)
  'coquitlam/women-s-men-s-health', // Women's/Men's Health (9 providers)
  'coquitlam/wrist-hand', // Wrist/Hand (11 providers)
  'coquitlam/yoga', // Yoga (6 providers)
  // kelowna
  'kelowna/ankle-foot', // Ankle/Foot (6 providers)
  'kelowna/back', // Back (6 providers)
  'kelowna/chronic-disease-management', // Chronic Disease Management (5 providers)
  'kelowna/eating-disorder-recovery', // Eating Disorder Recovery (5 providers)
  'kelowna/fitness', // Fitness (11 providers)
  'kelowna/headache', // Headache (5 providers)
  'kelowna/high-intensity-interval-training', // High Intensity Interval Training (6 providers)
  'kelowna/hip', // Hip (5 providers)
  'kelowna/knee', // Knee (6 providers)
  'kelowna/maternity-pre-and-postnatal', // Maternity/Pre and Postnatal (5 providers)
  'kelowna/mood-mental-health', // Mood/Mental Health (7 providers)
  'kelowna/neck', // Neck (6 providers)
  'kelowna/nutrition', // Nutrition (9 providers)
  'kelowna/pain-management', // Pain Management (9 providers)
  'kelowna/preventative-health', // Preventative Health (7 providers)
  'kelowna/shoulder', // Shoulder (6 providers)
  'kelowna/sports-specific-conditioning', // Sports Specific Conditioning (8 providers)
  'kelowna/strength-training-toning', // Strength Training/Toning (9 providers)
  'kelowna/weight-management', // Weight Management (5 providers)
  'kelowna/women-s-men-s-health', // Women's/Men's Health (12 providers)
  'kelowna/wrist-hand', // Wrist/Hand (6 providers)
  // richmond
  'richmond/mood-mental-health', // Mood/Mental Health (5 providers)
  // surrey
  'surrey/addiction', // Addiction (5 providers)
  'surrey/ankle-foot', // Ankle/Foot (11 providers)
  'surrey/attention-focus', // Attention/Focus (5 providers)
  'surrey/back', // Back (12 providers)
  'surrey/behavioural', // Behavioural (5 providers)
  'surrey/chronic-disease-management', // Chronic Disease Management (8 providers)
  'surrey/couples-family', // Couples/Family (5 providers)
  'surrey/depression', // Depression (12 providers)
  'surrey/digestion-and-gut-health', // Digestion and Gut Health (8 providers)
  'surrey/eating-disorder-recovery', // Eating Disorder Recovery (5 providers)
  'surrey/elbow', // Elbow (11 providers)
  'surrey/fitness', // Fitness (20 providers)
  'surrey/food-sensitivities', // Food Sensitivities (7 providers)
  'surrey/headache', // Headache (11 providers)
  'surrey/high-intensity-interval-training', // High Intensity Interval Training (9 providers)
  'surrey/hip', // Hip (11 providers)
  'surrey/hormone-imbalance', // Hormone Imbalance (9 providers)
  'surrey/immune-system-and-energy', // Immune System and Energy (5 providers)
  'surrey/jaw', // Jaw (5 providers)
  'surrey/knee', // Knee (11 providers)
  'surrey/mindfulness', // Mindfulness (10 providers)
  'surrey/mood-mental-health', // Mood/Mental Health (15 providers)
  'surrey/motivation', // Motivation (9 providers)
  'surrey/neck', // Neck (12 providers)
  'surrey/nutrition', // Nutrition (9 providers)
  'surrey/oral-care', // Oral Care (1 provider — dental focus)
  'surrey/pain-management', // Pain Management (17 providers)
  'surrey/preventative-health', // Preventative Health (11 providers)
  'surrey/running', // Running (12 providers)
  'surrey/shoulder', // Shoulder (12 providers)
  'surrey/sleep', // Sleep (6 providers)
  'surrey/sports-specific-conditioning', // Sports Specific Conditioning (13 providers)
  'surrey/strength-training-toning', // Strength Training/Toning (17 providers)
  'surrey/stress-anxiety', // Stress/Anxiety (13 providers)
  'surrey/trauma', // Trauma (7 providers)
  'surrey/weight-management', // Weight Management (8 providers)
  'surrey/women-s-men-s-health', // Women's/Men's Health (10 providers)
  'surrey/wrist-hand', // Wrist/Hand (11 providers)
  'surrey/yoga', // Yoga (6 providers)
  // vancouver
  'vancouver/addiction', // Addiction (14 providers)
  'vancouver/anger', // Anger (15 providers)
  'vancouver/ankle-foot', // Ankle/Foot (37 providers)
  'vancouver/attention-focus', // Attention/Focus (23 providers)
  'vancouver/back', // Back (39 providers)
  'vancouver/behavioural', // Behavioural (19 providers)
  'vancouver/chronic-disease-management', // Chronic Disease Management (22 providers)
  'vancouver/couples-family', // Couples/Family (9 providers)
  'vancouver/depression', // Depression (23 providers)
  'vancouver/digestion-and-gut-health', // Digestion and Gut Health (28 providers)
  'vancouver/eating-disorder', // Eating Disorder (18 providers)
  'vancouver/eating-disorder-recovery', // Eating Disorder Recovery (17 providers)
  'vancouver/elbow', // Elbow (35 providers)
  'vancouver/energy-healing', // Energy Healing (7 providers)
  'vancouver/fertility-adoption', // Fertility/Adoption (10 providers)
  'vancouver/fitness', // Fitness (43 providers)
  'vancouver/food-sensitivities', // Food Sensitivities (21 providers)
  'vancouver/headache', // Headache (38 providers)
  'vancouver/health-condition', // Health Condition (23 providers)
  'vancouver/high-intensity-interval-training', // High Intensity Interval Training (19 providers)
  'vancouver/hip', // Hip (36 providers)
  'vancouver/hormone-imbalance', // Hormone Imbalance (24 providers)
  'vancouver/hormones', // Hormones (33 providers)
  'vancouver/immune-system-and-energy', // Immune System and Energy (32 providers)
  'vancouver/iv-therapy', // IV Therapy (7 providers)
  'vancouver/jaw', // Jaw (24 providers)
  'vancouver/knee', // Knee (37 providers)
  'vancouver/learning-disability', // Learning Disability (6 providers)
  'vancouver/maternity-pre-and-postnatal', // Maternity/Pre and Postnatal (17 providers)
  'vancouver/medical-care', // Medical Care (8 providers)
  'vancouver/memory', // Memory (18 providers)
  'vancouver/menopause', // Menopause (23 providers)
  'vancouver/mindfulness', // Mindfulness (31 providers)
  'vancouver/mood-mental-health', // Mood/Mental Health (49 providers)
  'vancouver/motivation', // Motivation (20 providers)
  'vancouver/natural-holistic-remedies', // Natural/Holistic Remedies (21 providers)
  'vancouver/natural-remedies', // Natural Remedies (21 providers)
  'vancouver/neck', // Neck (37 providers)
  'vancouver/nutrition', // Nutrition (39 providers)
  'vancouver/oral-care', // Oral Care (2 providers — dental focus)
  'vancouver/pain-management', // Pain Management (53 providers)
  'vancouver/pilates', // Pilates (13 providers)
  'vancouver/pms', // PMS (22 providers)
  'vancouver/preventative-health', // Preventative Health (26 providers)
  'vancouver/reproductive-health-fertility', // Reproductive Health/Fertility (21 providers)
  'vancouver/running', // Running (16 providers)
  'vancouver/sexual-health', // Sexual Health (15 providers)
  'vancouver/shoulder', // Shoulder (35 providers)
  'vancouver/skin-health', // Skin Health (16 providers)
  'vancouver/skin-treatments', // Skin Treatments (7 providers)
  'vancouver/sleep', // Sleep (27 providers)
  'vancouver/sports-specific-conditioning', // Sports Specific Conditioning (18 providers)
  'vancouver/strength-training-toning', // Strength Training/Toning (25 providers)
  'vancouver/stress-anxiety', // Stress/Anxiety (31 providers)
  'vancouver/supplements', // Supplements (13 providers)
  'vancouver/trauma', // Trauma (17 providers)
  'vancouver/weight-management', // Weight Management (25 providers)
  'vancouver/women-s-men-s-health', // Women's/Men's Health (56 providers)
  'vancouver/wrist-hand', // Wrist/Hand (32 providers)
  'vancouver/yoga', // Yoga (6 providers)
  // victoria
  'victoria/back', // Back (5 providers)
  'victoria/chronic-disease-management', // Chronic Disease Management (5 providers)
  'victoria/depression', // Depression (5 providers)
  'victoria/fitness', // Fitness (6 providers)
  'victoria/headache', // Headache (5 providers)
  'victoria/hormones', // Hormones (6 providers)
  'victoria/immune-system-and-energy', // Immune System and Energy (6 providers)
  'victoria/jaw', // Jaw (5 providers)
  'victoria/maternity-pre-and-postnatal', // Maternity/Pre and Postnatal (5 providers)
  'victoria/menopause', // Menopause (5 providers)
  'victoria/mindfulness', // Mindfulness (5 providers)
  'victoria/mood-mental-health', // Mood/Mental Health (14 providers)
  'victoria/motivation', // Motivation (5 providers)
  'victoria/natural-holistic-remedies', // Natural/Holistic Remedies (5 providers)
  'victoria/neck', // Neck (5 providers)
  'victoria/nutrition', // Nutrition (7 providers)
  'victoria/pain-management', // Pain Management (11 providers)
  'victoria/pms', // PMS (5 providers)
  'victoria/preventative-health', // Preventative Health (6 providers)
  'victoria/reproductive-health-fertility', // Reproductive Health/Fertility (6 providers)
  'victoria/sleep', // Sleep (6 providers)
  'victoria/stress-anxiety', // Stress/Anxiety (6 providers)
  'victoria/women-s-men-s-health', // Women's/Men's Health (11 providers)
  // white_rock
  'white_rock/mood-mental-health', // Mood/Mental Health (5 providers)
];

const INDEXABLE_CITY_TYPE: ReadonlyArray<string> = [
  // burnaby
  'burnaby/counsellor', // Counsellor (5 providers)
  'burnaby/kinesiologist', // Kinesiologist (9 providers)
  'burnaby/life-wellness-coach', // Life/Wellness Coach (6 providers)
  'burnaby/naturopath', // Naturopath (5 providers)
  'burnaby/nutritionist', // Nutritionist (7 providers)
  'burnaby/personal-trainer', // Personal Trainer (6 providers)
  'burnaby/physiotherapist', // Physiotherapist (10 providers)
  'burnaby/registered-dietician', // Registered Dietician (5 providers)
  // coquitlam
  'coquitlam/counsellor', // Counsellor (6 providers)
  'coquitlam/kinesiologist', // Kinesiologist (8 providers)
  'coquitlam/life-wellness-coach', // Life/Wellness Coach (6 providers)
  'coquitlam/meditation-yoga-instructor', // Meditation/Yoga Instructor (5 providers)
  'coquitlam/nutritionist', // Nutritionist (6 providers)
  'coquitlam/personal-trainer', // Personal Trainer (9 providers)
  'coquitlam/physiotherapist', // Physiotherapist (7 providers)
  // kelowna
  'kelowna/personal-trainer', // Personal Trainer (5 providers)
  // surrey
  'surrey/counsellor', // Counsellor (5 providers)
  'surrey/kinesiologist', // Kinesiologist (7 providers)
  'surrey/life-wellness-coach', // Life/Wellness Coach (7 providers)
  'surrey/meditation-yoga-instructor', // Meditation/Yoga Instructor (5 providers)
  'surrey/nutritionist', // Nutritionist (8 providers)
  'surrey/personal-trainer', // Personal Trainer (10 providers)
  'surrey/physiotherapist', // Physiotherapist (7 providers)
  // vancouver
  'vancouver/acupuncturist', // Acupuncturist (9 providers)
  'vancouver/chiropractor', // Chiropractor (8 providers)
  'vancouver/counsellor', // Counsellor (7 providers)
  'vancouver/kinesiologist', // Kinesiologist (13 providers)
  'vancouver/life-wellness-coach', // Life/Wellness Coach (18 providers)
  'vancouver/meditation-yoga-instructor', // Meditation/Yoga Instructor (6 providers)
  'vancouver/naturopath', // Naturopath (11 providers)
  'vancouver/nutritionist', // Nutritionist (16 providers)
  'vancouver/osteopathic-manual-practitioners', // Osteopathic Manual Practitioners (5 providers)
  'vancouver/personal-trainer', // Personal Trainer (10 providers)
  'vancouver/physiotherapist', // Physiotherapist (17 providers)
  'vancouver/registered-dietician', // Registered Dietician (6 providers)
  'vancouver/registered-massage-therapist', // Registered Massage Therapist (6 providers)
  'vancouver/traditional-chinese-medicine', // Traditional Chinese Medicine (5 providers)
  // victoria
  'victoria/acupuncturist', // Acupuncturist (5 providers)
];

const cityCategorySet = new Set(INDEXABLE_CITY_CATEGORY);
const cityTypeSet = new Set(INDEXABLE_CITY_TYPE);

export function isIndexableCityCategory(city: string, categorySlug: string): boolean {
  if (!city || !categorySlug) return true;
  return cityCategorySet.has(`${city}/${categorySlug}`);
}

export function isIndexableCityType(city: string, typeSlug: string): boolean {
  if (!city || !typeSlug) return true;
  return cityTypeSet.has(`${city}/${typeSlug}`);
}
