// Auto-generated by scripts/generate-static-page-dates.js — do not edit manually
export const staticPageDates: { [route: string]: string } = {
  '/': '2026-04-16',
  '/about': '2026-04-16',
  '/about/partner': '2026-04-16',
  '/plans': '2026-04-16',
  '/plans/product': '2026-04-16',
  '/companies': '2026-04-16',
  '/ambassador-program': '2026-04-16',
  '/press-release': '2026-04-16',
  '/online-academy': '2026-04-16',
  '/testimonial': '2026-04-16',
  '/faq': '2026-04-16',
  '/subscribe/newsletter': '2026-04-16',
  '/contact-us': '2026-04-16',
  '/policy': '2026-04-16',
  '/terms': '2026-04-16',
};
