// Generated by scripts/generate-static-page-dates.js, which lists the pages and
// says where each date comes from. Edit the list there: this file is rewritten
// on every build, and a page with no date gets no <lastmod>.
export interface IStaticPage {
  route: string;
  lastmod: string | null;
  changefreq: string;
  priority: string | null;
}

export const staticPages: IStaticPage[] = [
  { route: '/', lastmod: '2026-09-23', changefreq: 'weekly', priority: '1.0' },
  { route: '/about', lastmod: '2026-04-16', changefreq: 'monthly', priority: null },
  { route: '/about/partner', lastmod: '2026-09-23', changefreq: 'monthly', priority: null },
  { route: '/about/editorial-standards', lastmod: '2026-05-01', changefreq: 'monthly', priority: null },
  { route: '/plans', lastmod: '2026-09-23', changefreq: 'monthly', priority: null },
  { route: '/for-practitioners', lastmod: '2026-09-23', changefreq: 'monthly', priority: null },
  { route: '/plans/product', lastmod: '2026-04-08', changefreq: 'monthly', priority: null },
  { route: '/companies', lastmod: '2026-04-02', changefreq: 'monthly', priority: null },
  { route: '/ambassador-program', lastmod: '2026-04-08', changefreq: 'monthly', priority: null },
  { route: '/press-release', lastmod: '2026-04-02', changefreq: 'monthly', priority: null },
  { route: '/online-academy', lastmod: '2026-09-23', changefreq: 'monthly', priority: null },
  { route: '/testimonial', lastmod: '2026-04-18', changefreq: 'monthly', priority: null },
  { route: '/faq', lastmod: '2026-04-04', changefreq: 'monthly', priority: null },
  { route: '/subscribe/newsletter', lastmod: '2026-09-23', changefreq: 'monthly', priority: null },
  { route: '/contact-us', lastmod: '2026-09-23', changefreq: 'monthly', priority: null },
  { route: '/policy', lastmod: '2026-09-01', changefreq: 'yearly', priority: null },
  { route: '/terms', lastmod: '2026-04-18', changefreq: 'yearly', priority: null },
  { route: '/medical-disclaimer', lastmod: '2026-04-21', changefreq: 'yearly', priority: null },
];
